#!name=general_list
#!desc=General settings

[General]
dns-server = https://1.1.1.1/dns-query#proxy
fallback-dns-server = https://cloudflare-dns.com/dns-query#proxy
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32, ff02::fb/128
ipv6 = false
prefer-ipv6 = false
dns-direct-system = true
icmp-auto-reply = true
private-ip-answer = false
dns-direct-fallback-proxy = true
udp-policy-not-supported-behaviour = REJECT
use-local-host-item-for-proxy = false
stun-response-ip = 1.1.1.1
stun-response-ipv6 = ::1