#!name=general_list
#!desc=General settings

[General]
dns-server = https://1.1.1.1/dns-query#proxy
fallback-dns-server = https://cloudflare-dns.com/dns-query#proxy
bypass-system = true
ipv6 = false
prefer-ipv6 = false
dns-direct-system = true
icmp-auto-reply = true
private-ip-answer = true
dns-direct-fallback-proxy = false
udp-policy-not-supported-behaviour = REJECT
use-local-host-item-for-proxy = false
close-if-proxy-chain-missing = true
hijack-dns = 8.8.8.8:53,8.8.4.4:53
stun-response-ip = 1.1.1.1
stun-response-ipv6 = ::1