#!name=sky_list
#!desc=Personal settings

[Rule]
DOMAIN-SUFFIX,yunat.com,DIRECT
DOMAIN-SUFFIX,shuyun.com,DIRECT
DOMAIN-SUFFIX,genmillscn.com,DIRECT
DOMAIN-SUFFIX,bing.com,DIRECT
DOMAIN-SUFFIX,openai.com,PROXY
DOMAIN-SUFFIX,chatgpt.com,PROXY
DOMAIN,www.wd-gold.net,PROXY
DOMAIN,api.wd-purple.com,DIRECT
DOMAIN,wd-purple.com,DIRECT

# Claude 相关域名
DOMAIN-SUFFIX,anthropic.com,PROXY
DOMAIN-SUFFIX,claude.ai,PROXY
DOMAIN-SUFFIX,claude.com,PROXY
DOMAIN-SUFFIX,clau.de,PROXY
DOMAIN-SUFFIX,claudemcpclient.com,PROXY
DOMAIN-SUFFIX,claudemcpcontent.com,PROXY
DOMAIN-SUFFIX,claudeusercontent.com,PROXY
DOMAIN,servd-anthropic-website.b-cdn.net,PROXY
DOMAIN,anthropic.com.cdn.cloudflare.net,PROXY
DOMAIN,anthropic.auth0.com,PROXY
DOMAIN,anthropic-com.ghost.io,PROXY
DOMAIN-SUFFIX,sentry.io,PROXY
DOMAIN-SUFFIX,statsigapi.net,PROXY
DOMAIN,browser-intake-us5-datadoghq.com,PROXY
DOMAIN-KEYWORD,datadog,PROXY
DOMAIN-KEYWORD,sift,PROXY
DOMAIN-SUFFIX,intercom.io,PROXY
DOMAIN-SUFFIX,intercomcdn.com,PROXY
DOMAIN,cdn.usefathom.com,PROXY
IP-CIDR,160.79.104.0/21,PROXY,no-resolve
IP-CIDR6,2607:6bc0::/32,PROXY,no-resolve
IP-ASN,399358,PROXY,no-resolve
