#!name=sky_list
#!desc=Personal settings

[Rule]
DOMAIN-SUFFIX,yunat.com,DIRECT
DOMAIN-SUFFIX,shuyun.com,DIRECT
DOMAIN-SUFFIX,genmillscn.com,DIRECT
DOMAIN-SUFFIX,bing.com,DIRECT
DOMAIN-SUFFIX,dmit.io,DIRECT
DOMAIN-SUFFIX,anthropic.com,PROXY
DOMAIN-SUFFIX,claude.ai,PROXY
DOMAIN-SUFFIX,openai.com,PROXY
DOMAIN-SUFFIX,chatgpt.com,PROXY
DOMAIN,www.wd-gold.net,PROXY
IP-CIDR,179.253.228.169/32,DIRECT,no-resolve